/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gnqpjcaxyvqsxqfjfalv";
export const SUPABASE_FUNCTIONS_BASE_URL =
  "https://gnqpjcaxyvqsxqfjfalv.supabase.co/functions/v1/server";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducXBqY2F4eXZxc3hxZmpmYWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNDkyMjcsImV4cCI6MjA4NDcyNTIyN30.-yWe_SQK164vwg6WUJ-vtSumBMTOEbADcayKaWGPQ84";

// ============================================================
// Supabase Edge Function 헤더 헬퍼
// ============================================================

/**
 * Supabase Edge Function 호출에 필요한 공통 헤더 생성
 *
 * 모든 Supabase Edge Function 호출에는 Authorization 헤더가 필수입니다.
 * 헤더가 없으면: {"code":401,"message":"Missing authorization header"}
 *
 * @param extra - 추가 헤더 (선택)
 * @returns HeadersInit 객체
 *
 * @example
 * // 기본 사용
 * fetch(url, { headers: getSupabaseHeaders() })
 *
 * @example
 * // POST 요청 (Content-Type 자동 포함)
 * fetch(url, {
 *   method: 'POST',
 *   headers: getSupabaseHeaders(),
 *   body: JSON.stringify(data)
 * })
 */
export function getSupabaseHeaders(extra?: HeadersInit): HeadersInit {
  return {
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${publicAnonKey}`,
    ...(extra ?? {}),
  };
}